name: Minify CSS and JS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install cssnano-cli
        npm install terser
    
    - name: Minify CSS files
      run: |
        npx cssnano css/merci.css css/merci.min.css
        npx cssnano css/offline.css css/offline.min.css
        npx cssnano css/style-site.css css/style-site.min.css
    
    - name: Minify JS files
      run: |
        npx terser js/email.js -o js/email.min.js
        npx terser js/main.js -o js/main.min.js
        npx terser js/tailwind-config.js -o js/tailwind-config.min.js
    
    - name: Commit and push minified files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add css/*.min.css js/*.min.js
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-minify CSS and JS files" && git push)