name: Minify CSS and JS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  minify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install -g cssnano-cli
        npm install -g terser
    
    - name: Minify CSS
      run: |
        cssnano merci.css merci.min.css
        cssnano offline.css offline.min.css
        cssnano style-site.css style-site.min.css
    
    - name: Minify JS
      run: |
        terser email.js -o email.min.js
        terser main.js -o main.min.js
        terser tailwind-config.js -o tailwind-config.min.js
    
    - name: Commit minified files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.min.css *.min.js
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-minify CSS and JS files"
        git push